services:
  traefik:
    image: traefik:3
    command: |
      --log.level=DEBUG
      --api.dashboard=true
      --providers.docker
      --entryPoints.web.address=:80
      --entryPoints.web.http.redirections.entryPoint.to=websecure
      --entryPoints.web.http.redirections.entryPoint.scheme=https
      --entryPoints.websecure.address=:443
      --certificatesresolvers.letsencrypt.acme.email=mail@dominik-schwaiger.ch
      --certificatesresolvers.letsencrypt.acme.storage=acme.json
      --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/raid5/traefik/auth:/auth
    labels:
      - "traefik.http.middlewares.test-auth.basicauth.usersfile=/auth/users"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.dominik-schwaiger.ch`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=letsencrypt